name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt;
      - name: Install MCD
        run: pip install .;
      - name: run tests
        run: python3 -m unittest discover -v;

  publish_build:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: test_build
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt;
      - name: Build MCD wheel
        run: python3 -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
