name: Publish code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt;
      - name: Install MCD
        run: pip install .;
      - name: run tests
        run: python3 -m unittest discover -v;
      - name: Build wheel
        run: python3 -m build;
      - name: Twine check
        run: twine check dist/*
      - name: Twine upload
        run: twine upload dist/*
